version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:17.05.0-ce-git      
    steps:
      - checkout
      - setup_remote_docker     
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0            
            pip install awscli
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
      - deploy:
          name: Push application Docker image
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:latest
            docker push $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/dockerapp:latest


  deploy:  
    docker:
      - image: circleci/python:3.6.1
    environment:
      AWS_DEFAULT_OUTPUT: json
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace      
      - run:
          name: Install awscli
          command: |
            python3 -m venv venv
            . venv/bin/activate   
            pip install awscli>=1.15.50
      - run: 
          name: Chmod add permissions to Shell 2
          command:            
            chmod +x deploy.sh    
      - run:
          name: Setup common environment variables
          command: |
            echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
            echo 'export ECS_CLUSTER_NAME="dockerapp-cluster"' >> $BASH_ENV
            echo 'export ECS_SERVICE_NAME="dockerapp-service"' >> $BASH_ENV
      - run:
          name: Push image on ECR
          command: |
            . venv/bin/activate
            eval $(aws ecr get-login --region $AWS_REGION --no-include-email)
            docker push 438693937837.dkr.ecr.us-east-2.amazonaws.com/dockerapp:$CIRCLE_SHA1
      - run:
          name: Deploy on ECS
          command: |
            . venv/bin/activate
            export ECS_TASK_FAMILY_NAME="${AWS_RESOURCE_NAME_PREFIX}-service"
            export ECS_CONTAINER_DEFINITION_NAME="${AWS_RESOURCE_NAME_PREFIX}-service"
            export EXECUTION_ROLE_ARN="arn:aws:iam::438693937837:role/ecsTaskExecutionRole"
            ./deploy.sh
     
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build